# -*- coding: utf-8 -*-
"""
Generate a 16x16 bitmap CJK font (GB2312 level-1, 3755 chars) as a C header.

Output: include/cn_font.h
  - cn_font16[3755][32]   bitmap data, row-major, 16 rows x 2 bytes
  - cn_index[]            unicode -> glyph slot lookup table
  - CN_FONT_COUNT

Lookup at runtime: linear/binary search over cn_index (sorted by unicode).
"""

import os
import struct
from PIL import Image, ImageDraw, ImageFont

FONT_PATH = r"C:\Windows\Fonts\simhei.ttf"
SIZE = 16
OUT_H = r"D:\学习\TFT169_ESP32S3\include\cn_font.h"


def gb2312_level1_chars():
    """Yield the 3755 level-1 GB2312 hanzi, in GB2312 code order."""
    chars = []
    for hi in range(0xB0, 0xD8):          # area 16..55
        for lo in range(0xA1, 0xFF):
            try:
                b = bytes([hi, lo])
                ch = b.decode("gb2312")
                chars.append(ch)
            except UnicodeDecodeError:
                continue
    return chars


def render_glyph(font, ch):
    """Render one char to a 16x16 1-bit bitmap, return 32 bytes."""
    img = Image.new("1", (SIZE, SIZE), 0)
    d = ImageDraw.Draw(img)

    # center the glyph inside the 16x16 cell
    try:
        bbox = d.textbbox((0, 0), ch, font=font)
    except Exception:
        bbox = (0, 0, SIZE, SIZE)
    gw = bbox[2] - bbox[0]
    gh = bbox[3] - bbox[1]
    ox = (SIZE - gw) // 2 - bbox[0]
    oy = (SIZE - gh) // 2 - bbox[1]

    d.text((ox, oy), ch, font=font, fill=1)

    px = img.load()
    out = bytearray()
    for y in range(SIZE):
        hi = 0
        lo = 0
        for x in range(8):
            if px[x, y]:
                hi |= (0x80 >> x)
        for x in range(8, 16):
            if px[x, y]:
                lo |= (0x80 >> (x - 8))
        out.append(hi)
        out.append(lo)
    return bytes(out)


def main():
    chars = gb2312_level1_chars()
    print("GB2312 level-1 chars:", len(chars))

    font = ImageFont.truetype(FONT_PATH, SIZE)

    glyphs = []
    index = []
    for ch in chars:
        cp = ord(ch)
        glyphs.append(render_glyph(font, ch))
        index.append(cp)

    # sort by codepoint for binary search
    paired = sorted(zip(index, glyphs))
    index = [p[0] for p in paired]
    glyphs = [p[1] for p in paired]

    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)

    with open(OUT_H, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Auto-generated by tools/gen_font.py -- do not edit\n")
        f.write("// 16x16 bitmap CJK font, GB2312 level-1, %d glyphs\n" % len(glyphs))
        f.write("// Each glyph: 16 rows x 2 bytes, MSB first, 1 = pixel on\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define CN_FONT_W 16\n")
        f.write("#define CN_FONT_H 16\n")
        f.write("#define CN_FONT_COUNT %d\n\n" % len(glyphs))

        # index table: uint16 codepoints are not enough (some > 0xFFFF),
        # use uint32 for safety
        f.write("static const uint32_t cn_font_index[CN_FONT_COUNT] = {\n")
        for i in range(0, len(index), 12):
            row = ", ".join("0x%04X" % c for c in index[i:i + 12])
            f.write("  " + row + ",\n")
        f.write("};\n\n")

        f.write("static const uint8_t cn_font16[CN_FONT_COUNT][32] = {\n")
        for g in glyphs:
            row = ", ".join("0x%02X" % b for b in g)
            f.write("  {" + row + "},\n")
        f.write("};\n")

    size = os.path.getsize(OUT_H)
    print("written:", OUT_H)
    print("size: %.1f KB" % (size / 1024.0))
    print("glyphs:", len(glyphs))
    print("index range: U+%04X .. U+%04X" % (index[0], index[-1]))


if __name__ == "__main__":
    main()
